version: '2'
services:
  myerp.db:
    image: postgres
    restart: always
    ports:
      - "192.168.99.101:9032:5432"
    volumes:
       - "./init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_DB=db_myerp
      - POSTGRES_USER=usr_myerp
      - POSTGRES_PASSWORD=myerp
